export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESSFUL';

export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';


export const AUTH_USER_REGISTER_SUCCESSFUL = 'AUTH_USER_REGISTER_SUCCESSFUL';
export const AUTH_USER_SIGN_IN_SUCCESSFUL = 'AUTH_USER_SIGN_IN_SUCCESSFUL';
export const AUTH_USER_SIGN_IN_FAILURE = 'AUTH_USER_SIGN_IN_FAILURE';

export const AUTH_USER_STAY_UP = 'AUTH_USER_STAY_UP';

export const ADD_MEAL = "ADD_MEAL"


